simulation:
  dt: 0.5
  method: "closeness" # closeness or emptiness
  maxIterations: 1000
  turnstileCount: 5
  turnstileWidth: 1.2
  corridorLength: 2.0
board:
  dimL: 15
  cellLineCount: 5  # L10, C8 -> 1.25m per cell
agents:
  maxCount: 100
  mass: 80.0
  minD: 0.5
  maxD: 0.7
  desiredSpeed: 0.1
sfm:
  kn: 120000
  kt: 240000
  A_a: 200.0
  A_w: 200.0
  B_a: 0.1
  B_w: 0.08
  tau: 0.5