simulation:
  dt: 0.25
  method: "closeness" # closeness or emptiness
  maxIterations: 1000
  turnstileCount: 5
  turnstileWidth: 1.2
  corridorLength: 2.0
board:
  dimL: 15
  cellLineCount: 5  # L10, C8 -> 1.25m per cell
agents:
  maxCount: 100
  mass: 80.0
  minD: 0.5
  maxD: 0.7
  desiredSpeed: 0.1
sfm:
  kn: 120
  kt: 240
  A_a: 10.0
  A_w: 15.0
  B_a: 0.1
  B_w: 0.06
  tau: 0.5