simulation:
  dt: 0.25
  method: "closeness" # closeness or emptiness
  maxIterations: 2800
  turnstileCount: 2
  turnstileWidth: 2.0
  corridorLength: 7.0
board:
  dimL: 20
  cellLineCount: 5  # L10, C8 -> 1.25m per cell
agents:
  maxCount: 100
  mass: 80.0
  minD: 0.5
  maxD: 0.7
  desiredSpeed: 0.1
sfm:
  kn: 100
  kt: 200
  A_a: 30.0
  A_w: 50.0
  B_a: 0.1
  B_w: 0.025
  tau: 0.5